import React, { useEffect, useCallback } from 'react';
import { useDeckStore } from '../../store/deckStore';
import { formatDimension } from '../../utils/units';
import './Toolbar.css';

function exportPDF() {
  import('jspdf').then(({ jsPDF }) => {
    const state = useDeckStore.getState();
    const { deck, calcs, bom, sqft } = state;
    const doc = new jsPDF('p', 'mm', 'letter');

    doc.setFillColor(10, 22, 40);
    doc.rect(0, 0, 216, 30, 'F');
    doc.setTextColor(59, 130, 246);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('DeckForge', 14, 18);
    doc.setTextColor(148, 163, 184);
    doc.setFontSize(10);
    doc.text('Deck Design & Material Report', 14, 25);
    doc.setTextColor(245, 158, 11);
    doc.text(`${formatDimension(deck.width)} × ${formatDimension(deck.depth)}  •  ${sqft} sq ft`, 160, 18);

    let y = 40;
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('Deck Specifications', 14, y);
    y += 8;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const specs = [
      ['Width', formatDimension(deck.width)],
      ['Depth', formatDimension(deck.depth)],
      ['Height', formatDimension(deck.height)],
      ['Square Footage', `${sqft} sq ft`],
      ['Lumber Species', deck.species],
      ['Joist Size', deck.joistSize],
      ['Joist Spacing', `${deck.joistSpacing}" o.c.`],
      ['Beam Config', deck.beamConfig],
      ['Post Size', deck.postSize],
      ['Deck Board', deck.deckBoardSize || '5/4x6'],
      ['Ledger', deck.ledgerAttached ? 'Attached' : 'Freestanding'],
      ['Soil Capacity', `${deck.soilCapacity} psf`],
    ];
    specs.forEach(([label, value]) => {
      doc.setTextColor(100, 116, 139);
      doc.text(label, 14, y);
      doc.setTextColor(30, 41, 59);
      doc.setFont('helvetica', 'bold');
      doc.text(value, 80, y);
      doc.setFont('helvetica', 'normal');
      y += 5.5;
    });

    y += 6;
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text('Structural Summary', 14, y);
    y += 8;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const structural = [
      ['Max Joist Span', formatDimension(calcs.joists.maxSpan)],
      ['Joist Count', String(calcs.joists.count)],
      ['Beam Count', String(calcs.beams.count)],
      ['Post Count', String(calcs.posts.posts.length)],
      ['Footing Diameter', `${calcs.footings.diameter}"`],
      ['Tributary Area', `${calcs.footings.tributaryArea} sq ft`],
    ];
    structural.forEach(([label, value]) => {
      doc.setTextColor(100, 116, 139);
      doc.text(label, 14, y);
      doc.setTextColor(30, 41, 59);
      doc.setFont('helvetica', 'bold');
      doc.text(value, 80, y);
      doc.setFont('helvetica', 'normal');
      y += 5.5;
    });

    y += 6;
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text('Bill of Materials', 14, y);
    y += 8;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 116, 139);
    doc.text('Description', 14, y);
    doc.text('Size', 100, y);
    doc.text('Length', 120, y);
    doc.text('Qty', 145, y);
    doc.text('Unit', 160, y);
    doc.text('Material', 175, y);
    y += 2;
    doc.setDrawColor(200, 210, 220);
    doc.line(14, y, 200, y);
    y += 4;

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30, 41, 59);
    bom.forEach((item) => {
      if (y > 260) { doc.addPage(); y = 20; }
      doc.text(item.description, 14, y);
      doc.text(item.size, 100, y);
      doc.text(item.length ? `${item.length}'` : '—', 120, y);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(245, 158, 11);
      doc.text(String(item.quantity), 145, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(30, 41, 59);
      doc.text(item.unit, 160, y);
      doc.text(item.material, 175, y);
      y += 5;
    });

    y += 3;
    doc.setDrawColor(200, 210, 220);
    doc.line(14, y, 200, y);
    y += 5;
    doc.setFont('helvetica', 'bold');
    doc.text('Total Parts:', 100, y);
    doc.setTextColor(245, 158, 11);
    const totalParts = bom.reduce((sum, item) => sum + item.quantity, 0);
    doc.text(totalParts.toLocaleString(), 145, y);

    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(7);
      doc.setTextColor(148, 163, 184);
      doc.text('Generated by DeckForge  •  IRC R507 Compliant  •  For estimation purposes only', 14, 272);
      doc.text(`Page ${i} of ${pageCount}`, 190, 272);
    }

    doc.save(`DeckForge_${deck.width / 12}x${deck.depth / 12}_${new Date().toISOString().slice(0, 10)}.pdf`);
  }).catch((err) => {
    console.error('Failed to load jsPDF:', err);
    alert('PDF export requires an internet connection for the first use.');
  });
}

export default function Toolbar({ isMobile }) {
  const viewMode = useDeckStore((s) => s.viewMode);
  const setViewMode = useDeckStore((s) => s.setViewMode);
  const undo = useDeckStore((s) => s.undo);
  const redo = useDeckStore((s) => s.redo);
  const historyIndex = useDeckStore((s) => s.historyIndex);
  const historyLength = useDeckStore((s) => s.history.length);
  const deck = useDeckStore((s) => s.deck);
  const sqft = useDeckStore((s) => s.sqft);

  // Keyboard shortcuts
  const handleKeyDown = useCallback((e) => {
    const isMeta = e.metaKey || e.ctrlKey;
    if (isMeta && e.key === 'z' && !e.shiftKey) { e.preventDefault(); undo(); }
    if (isMeta && e.key === 'z' && e.shiftKey) { e.preventDefault(); redo(); }
    if (isMeta && e.key === 'y') { e.preventDefault(); redo(); }
    if (e.key === '2' && !e.metaKey && !e.ctrlKey && !e.target.closest('input, select')) setViewMode('2d');
    if (e.key === '3' && !e.metaKey && !e.ctrlKey && !e.target.closest('input, select')) setViewMode('3d');
  }, [undo, redo, setViewMode]);

  useEffect(() => {
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [handleKeyDown]);

  if (isMobile) {
    return (
      <header className="toolbar toolbar--mobile" id="main-toolbar">
        <div className="toolbar__brand toolbar__brand--mobile">
          <span className="toolbar__title toolbar__title--mobile">DeckForge</span>
        </div>

        <div className="toolbar__view-toggle toolbar__view-toggle--mobile">
          <button
            className={`btn btn--ghost toolbar__view-btn ${viewMode === '2d' ? 'btn--active' : ''}`}
            onClick={() => setViewMode('2d')}
            id="btn-view-2d"
          >2D</button>
          <button
            className={`btn btn--ghost toolbar__view-btn ${viewMode === '3d' ? 'btn--active' : ''}`}
            onClick={() => setViewMode('3d')}
            id="btn-view-3d"
          >3D</button>
        </div>

        <div className="toolbar__mobile-dims font-mono">
          {formatDimension(deck.width)} × {formatDimension(deck.depth)}
        </div>

        <div style={{ flex: 1 }} />

        {/* Undo/Redo */}
        <button className="btn btn--ghost btn--icon" onClick={undo} disabled={historyIndex <= 0} aria-label="Undo" id="btn-undo">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <polyline points="1 4 1 10 7 10"/><path d="M3.51 15a9 9 0 1 0 2.13-9.36L1 10"/>
          </svg>
        </button>
        <button className="btn btn--ghost btn--icon" onClick={redo} disabled={historyIndex >= historyLength - 1} aria-label="Redo" id="btn-redo">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 1 1-2.13-9.36L23 10"/>
          </svg>
        </button>

        <button className="btn btn--primary btn--icon toolbar__export-mobile" onClick={exportPDF} aria-label="Export PDF" id="btn-export">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
            <polyline points="7 10 12 15 17 10"/>
            <line x1="12" y1="15" x2="12" y2="3"/>
          </svg>
        </button>
      </header>
    );
  }

  // Desktop toolbar
  return (
    <header className="toolbar" id="main-toolbar" role="toolbar" aria-label="Main toolbar">
      <div className="toolbar__brand">
        <div className="toolbar__logo">
          <svg width="24" height="24" viewBox="0 0 64 64" fill="none">
            <defs>
              <linearGradient id="tg" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stopColor="#3b82f6"/>
                <stop offset="100%" stopColor="#8b5cf6"/>
              </linearGradient>
            </defs>
            <rect x="4" y="28" width="56" height="6" rx="2" fill="url(#tg)"/>
            <rect x="8" y="36" width="4" height="20" rx="1" fill="#3b82f6" opacity="0.8"/>
            <rect x="26" y="36" width="4" height="24" rx="1" fill="#3b82f6" opacity="0.8"/>
            <rect x="52" y="36" width="4" height="20" rx="1" fill="#3b82f6" opacity="0.8"/>
            <rect x="6" y="22" width="52" height="4" rx="1" fill="#f59e0b" opacity="0.9"/>
            <rect x="6" y="16" width="52" height="4" rx="1" fill="#f59e0b" opacity="0.7"/>
            <rect x="6" y="10" width="52" height="4" rx="1" fill="#f59e0b" opacity="0.5"/>
          </svg>
        </div>
        <span className="toolbar__title">DeckForge</span>
      </div>

      <div className="toolbar__group">
        <div className="toolbar__view-toggle" role="radiogroup" aria-label="Viewport mode">
          <button className={`btn btn--ghost toolbar__view-btn ${viewMode === '2d' ? 'btn--active' : ''}`} onClick={() => setViewMode('2d')} id="btn-view-2d" role="radio" aria-checked={viewMode === '2d'}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="3" width="18" height="18" rx="2"/><line x1="3" y1="9" x2="21" y2="9"/><line x1="9" y1="3" x2="9" y2="21"/></svg>
            2D
          </button>
          <button className={`btn btn--ghost toolbar__view-btn ${viewMode === '3d' ? 'btn--active' : ''}`} onClick={() => setViewMode('3d')} id="btn-view-3d" role="radio" aria-checked={viewMode === '3d'}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 2L2 7l10 5 10-5-10-5z"/><path d="M2 17l10 5 10-5"/><path d="M2 12l10 5 10-5"/></svg>
            3D
          </button>
        </div>
      </div>

      <div className="toolbar__group toolbar__dims">
        <span className="toolbar__dim-label">{formatDimension(deck.width)} × {formatDimension(deck.depth)}</span>
        <span className="badge">{sqft} sq ft</span>
      </div>

      <div className="toolbar__group">
        <button className="btn btn--ghost btn--icon" onClick={undo} disabled={historyIndex <= 0} aria-label="Undo (Ctrl+Z)" title="Undo (Ctrl+Z)" id="btn-undo">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="1 4 1 10 7 10"/><path d="M3.51 15a9 9 0 1 0 2.13-9.36L1 10"/></svg>
        </button>
        <button className="btn btn--ghost btn--icon" onClick={redo} disabled={historyIndex >= historyLength - 1} aria-label="Redo (Ctrl+Shift+Z)" title="Redo (Ctrl+Shift+Z)" id="btn-redo">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 1 1-2.13-9.36L23 10"/></svg>
        </button>
      </div>

      <div style={{ flex: 1 }} />

      <div className="toolbar__group">
        <button className="btn btn--primary" id="btn-export" onClick={exportPDF} aria-label="Export PDF report">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
          Export PDF
        </button>
      </div>
    </header>
  );
}
